version: "3.7"
services:
    api:
        image: shopping:latest
        environment: 
            - ConnectionStrings__shopping=server=sql;database=shopping;user id=SA;password=Tokyo_Joe
        ports:
            - 8080:80
        networks:
            - my-network
    sql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Tokyo_Joe
            - MSSQL_PID=developer
        
        networks:
            - my-network
networks:
    my-network:
        driver: bridge